"use client";

import "./globals.css";
import "@/styles/index.scss";
import "rc-slider/assets/index.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import LayoutClientChild from "../components/layout-client-child";
import { Amplify } from "aws-amplify";
import config from '../amplifyconfiguration.json';
import { QueryClient, QueryClientProvider } from "react-query";
import ErrorBoundary from "@/components/ErrorBoundary";
import Head from "next/head";
import { AuthProvider } from "@/context/auth/AuthContext";

const queryClient = new QueryClient();

Amplify.configure(config);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Head>
        <title>Senior Project - Owner</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <ErrorBoundary>
        <QueryClientProvider client={queryClient}>
          <AuthProvider>
            <LayoutClientChild>
              {children}

              <ToastContainer />
            </LayoutClientChild>
          </AuthProvider>
        </QueryClientProvider>
      </ErrorBoundary>
    </>
  );
}
